export type Perfume = {
  id: string
  slug: string
  name: string
  category: string
  description: string
  price: number // price in cents
  priceFormatted: string
  image: string
  notes: {
    top: string[]
    heart: string[]
    base: string[]
  }
  tags: string[]
  collections?: string[]
  highlighted?: boolean
}

const formatPrice = (value: number) =>
  new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    minimumFractionDigits: 2,
  }).format(value / 100)

export const perfumes: Perfume[] = [
  {
    id: "ameixa-noir",
    slug: "ameixa-noir",
    name: "Ameixa Noir",
    category: "Eau de Parfum",
    description: "Notas profundas de ameixa preta envoltas em baunilha dourada e patchouli.",
    price: 28900,
    priceFormatted: formatPrice(28900),
    image: "/purple-plum-perfume-bottle-elegant-gold-details.jpg",
    notes: {
      top: ["ameixa negra", "bergamota"],
      heart: ["baunilha", "jasmim"],
      base: ["patchouli", "âmbar"],
    },
    tags: ["intenso", "noturno", "baunilha"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "jabuticaba-mystique",
    slug: "jabuticaba-mystique",
    name: "Jabuticaba Mystique",
    category: "Eau de Parfum",
    description: "Essência artesanal de jabuticaba com acordes amadeirados sofisticados.",
    price: 32900,
    priceFormatted: formatPrice(32900),
    image: "/jabuticaba-perfume-bottle-luxury-purple-gold.jpg",
    notes: {
      top: ["jabuticaba fresca"],
      heart: ["madeiras nobres", "rosa negra"],
      base: ["cedro", "almíscar"],
    },
    tags: ["amadeirado", "frutado", "exclusivo"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "uva-velvet",
    slug: "uva-velvet",
    name: "Uva Velvet",
    category: "Eau de Parfum",
    description: "Frescor das uvas com notas florais delicadas e toque aveludado.",
    price: 26900,
    priceFormatted: formatPrice(26900),
    image: "/grape-perfume-bottle-elegant-violet-gold-accents.jpg",
    notes: {
      top: ["uvas rubi", "peônia"],
      heart: ["lótus", "magnólia"],
      base: ["almíscar branco"],
    },
    tags: ["aveludado", "floral", "sofisticado"],
    collections: ["Purple Soul"],
  },
  {
    id: "figo-roxo-imperial",
    slug: "figo-roxo-imperial",
    name: "Figo Roxo Imperial",
    category: "Parfum",
    description: "Perfume opulento com figo roxo caramelizado e especiarias orientais.",
    price: 34900,
    priceFormatted: formatPrice(34900),
    image: "/elegant-purple-fig-perfume-bottle-with-gold-detail.jpg",
    notes: {
      top: ["figo roxo", "cardamomo"],
      heart: ["rosa damascena", "violeta"],
      base: ["cedro", "oud"],
    },
    tags: ["especiado", "luxuoso", "oriental"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "amora-sublime",
    slug: "amora-sublime",
    name: "Amora Sublime",
    category: "Eau de Parfum",
    description: "Intensa amora silvestre com toques de rosa búlgara e musk cremoso.",
    price: 30900,
    priceFormatted: formatPrice(30900),
    image: "/blackberry-perfume-bottle-purple-gold-luxury.jpg",
    notes: {
      top: ["amora silvestre", "mandarina"],
      heart: ["rosa búlgara", "ylang-ylang"],
      base: ["almíscar cremoso", "sândalo"],
    },
    tags: ["floral", "romântico", "cremoso"],
    collections: ["Purple Soul"],
  },
  {
    id: "acai-nebular",
    slug: "acai-nebular",
    name: "Açaí Nebular",
    category: "Eau de Toilette",
    description: "Vibrante combinação de açaí com notas terrosas e frescor herbal.",
    price: 20300,
    priceFormatted: formatPrice(20300),
    image: "/perfumeFei.png",
    notes: {
      top: ["açaí", "limão siciliano"],
      heart: ["folhas verdes", "lavanda"],
      base: ["vetiver", "cedro"],
    },
    tags: ["herbal", "vibrante", "diurno"],
    collections: ["Purple Soul"],
  },
  {
    id: "mirtilo-elegant",
    slug: "mirtilo-elegant",
    name: "Mirtilo Élégant",
    category: "Eau de Parfum",
    description: "Perfume refrescante com mirtilo cristalino e bouquet floral moderno.",
    price: 27900,
    priceFormatted: formatPrice(27900),
    image: "/mirtiloFei.jpeg",
    notes: {
      top: ["mirtilo", "pêra"],
      heart: ["íris", "peônia branca"],
      base: ["cashmere", "almíscar"],
    },
    tags: ["refrescante", "moderno", "leve"],
    collections: ["Purple Soul"],
  },
  {
    id: "cereja-roxo-romantica",
    slug: "cereja-roxo-romantica",
    name: "Cereja Roxa Romântica",
    category: "Eau de Parfum",
    description: "Notas suculentas de cereja roxa envolvidas por pétalas acetinadas.",
    price: 29900,
    priceFormatted: formatPrice(29900),
    image: "/purple-cherry-perfume-bottle-romantic.jpg",
    notes: {
      top: ["cereja roxa", "groselha"],
      heart: ["rosa centifolia", "lírio"],
      base: ["fava tonka", "cedro branco"],
    },
    tags: ["frutado", "romântico", "doce"],
    collections: ["Purple Soul"],
  },
  {
    id: "groselha-negra-noir",
    slug: "groselha-negra-noir",
    name: "Groselha Negra Noir",
    category: "Parfum",
    description: "Essência intensa com groselha negra e acorde de couro elegante.",
    price: 31900,
    priceFormatted: formatPrice(31900),
    image: "/black-currant-perfume-bottle-luxury.jpg",
    notes: {
      top: ["groselha negra", "pimenta rosa"],
      heart: ["violeta", "chá preto"],
      base: ["couro", "vetiver"],
    },
    tags: ["dramático", "couro", "noturno"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "ameixa-seca-royal",
    slug: "ameixa-seca-royal",
    name: "Ameixa Seca Royal",
    category: "Parfum",
    description: "Fragrância rica com ameixa seca, mel de acácia e incenso dourado.",
    price: 33900,
    priceFormatted: formatPrice(33900),
    image: "/ameixaFeia.jpg",
    notes: {
      top: ["ameixa seca", "cassis"],
      heart: ["mel", "flor de laranjeira"],
      base: ["incenso", "âmbar cinza"],
    },
    tags: ["gourmand", "opulento", "quente"],
    collections: ["Purple Soul"],
  },
  {
    id: "sabugueiro-mystic",
    slug: "sabugueiro-mystic",
    name: "Sabugueiro Mystic",
    category: "Eau de Parfum",
    description: "Perfume misterioso com flor de sabugueiro e nuances resinosas.",
    price: 28900,
    priceFormatted: formatPrice(28900),
    image: "/sabugoFei.jpg",
    notes: {
      top: ["flor de sabugueiro", "lima-da-pérsia"],
      heart: ["incienso branco", "violeta"],
      base: ["resinas âmbar", "madeira de cashmere"],
    },
    tags: ["místico", "resinoso", "artesanal"],
    collections: ["Purple Soul"],
  },
  {
    id: "aronia-power",
    slug: "aronia-power",
    name: "Aronia Power",
    category: "Eau de Toilette",
    description: "Essência energética de arônia com especiarias frias e musk limpo.",
    price: 25900,
    priceFormatted: formatPrice(25900),
    image: "/aronia-perfume-bottle-power.jpg",
    notes: {
      top: ["aronia", "pimenta sichuan"],
      heart: ["folha de violeta", "chá branco"],
      base: ["almíscar limpo", "cedro"],
    },
    tags: ["vibrante", "clean", "energético"],
    collections: ["Purple Soul"],
  },
  // {
  //   id: "mirtilo-vermelho-fresh",
  //   slug: "mirtilo-vermelho-fresh",
  //   name: "Mirtilo Vermelho Fresh",
  //   category: "Eau de Parfum",
  //   description: "Fragrância fresca e vivaz com combinação única de doçura e acidez.",
  //   price: 24900,
  //   priceFormatted: formatPrice(24900),
  //   image: "/cranberry-perfume-bottle-fresh.jpg",
  //   notes: {
  //     top: ["Mirtilo Vermelho", "Laranja", "Limão"],
  //     heart: ["Rosa", "Jasmim", "Lavanda"],
  //     base: ["Almíscar", "Sândalo", "Cedro"],
  //   },
  //   tags: ["refrescante", "vivaz", "casual"],
  //   collections: ["Purple Soul"],
  // },
  {
    id: "ouro-solar",
    slug: "ouro-solar",
    name: "Ouro Solar",
    category: "Parfum",
    description: "Bergamota italiana cintilante, pimenta rosa e âmbar luminoso criam um rastro solar.",
    price: 36900,
    priceFormatted: formatPrice(36900),
    image: "/GoldCollection/ouro-solar-perfume.jpg",
    notes: {
      top: ["Bergamota Italiana", "Pimenta Rosa"],
      heart: ["Flor de Laranjeira", "Néroli", "Lavanda Provençal"],
      base: ["Âmbar Solar", "Cedro Dourado", "Musk Radiante"],
    },
    tags: ["cítrico", "solar", "especiado"],
    collections: ["Golden Aura"],
    highlighted: true,
  },
  {
    id: "mel-de-safra",
    slug: "mel-de-safra",
    name: "Mel de Safra",
    category: "Parfum",
    description: "Mel de acácia caramelizado encontra flor de laranjeira e sândalo creme artesanal.",
    price: 38900,
    priceFormatted: formatPrice(38900),
    image: "/GoldCollection/mel-safra-perfume.jpg",
    notes: {
      top: ["Mel de Acácia", "Mandarina Doce"],
      heart: ["Flor de Laranjeira", "Gardênia", "Jasmim Mel"],
      base: ["Sândalo Creme", "Baunilha Fava", "Âmbar Dourado"],
    },
    tags: ["gourmand", "floral", "cremoso"],
    collections: ["Golden Aura"],
  },
  {
    id: "ambar-aurora",
    slug: "ambar-aurora",
    name: "Âmbar Aurora",
    category: "Parfum",
    description: "Âmbar resinoso com fava tonka, figo dourado e incenso branco etéreo.",
    price: 39900,
    priceFormatted: formatPrice(39900),
    image: "/GoldCollection/amber-aurora-perfume.jpg",
    notes: {
      top: ["Figo Dourado", "Pêssego Branco"],
      heart: ["Âmbar Vivo", "Benjoim", "Jasmim Absoluto"],
      base: ["Fava Tonka", "Incenso Branco", "Madeira de Cashmere"],
    },
    tags: ["resinoso", "sofisticado", "opulento"],
    collections: ["Golden Aura"],
  },
  {
    id: "champanhe-velours",
    slug: "champanhe-velours",
    name: "Champanhe Velours",
    category: "Eau de Parfum",
    description: "Pera cristalina, champanhe rosé e almíscar cremoso para um brilho festivo.",
    price: 41900,
    priceFormatted: formatPrice(41900),
    image: "/GoldCollection/champagne-velours-perfume.jpg",
    notes: {
      top: ["Champanhe Rosé", "Pera Cristal", "Framboesa Clara"],
      heart: ["Peônia Rosa", "Flor de Laranjeira", "Íris Aveludada"],
      base: ["Almíscar Cremoso", "Baunilha", "Cedro Branco"],
    },
    tags: ["efervescente", "floral", "aveludado"],
    collections: ["Golden Aura"],
    highlighted: true,
  },
  {
    id: "framboesa-carmesim",
    slug: "framboesa-carmesim",
    name: "Framboesa Carmesim",
    category: "Eau de Parfum",
    description: "Framboesa madura com lichia cintilante e pétalas cristalinas.",
    price: 32900,
    priceFormatted: formatPrice(32900),
    image: "/RedCollection/RasberryFragance.jpg",
    notes: {
      top: ["Framboesa Silvestre", "Lichia Rubra", "Limão Siciliano"],
      heart: ["Pétalas Cristalinas", "Magnólia", "Rosa Chá"],
      base: ["Âmbar Translúcido", "Musk Branco", "Sândalo Leve"],
    },
    tags: ["frutado", "efervescente", "doce"],
    collections: ["Red Bloom"],
    highlighted: true,
  },
  {
    id: "roma-royale",
    slug: "roma-royale",
    name: "Romã Royale",
    category: "Parfum",
    description: "Romã rubra envolta em madeira cerejeira e baunilha tostada.",
    price: 34900,
    priceFormatted: formatPrice(34900),
    image: "/RedCollection/pomegranate-royale-perfume.jpg",
    notes: {
      top: ["Romã Rubra", "Groselha Escura"],
      heart: ["Madeira de Cerejeira", "Jasmim Noite"],
      base: ["Baunilha Dourada", "Patchouli", "Âmbar Rubro"],
    },
    tags: ["suculento", "envolvente", "sensual"],
    collections: ["Red Bloom"],
  },
  {
    id: "pitanga-aurora",
    slug: "pitanga-aurora",
    name: "Pitanga Aurora",
    category: "Eau de Parfum",
    description: "Pitanga brasileira vibrante com cardamomo rosé e fava tonka.",
    price: 30900,
    priceFormatted: formatPrice(30900),
    image: "/RedCollection/pitanga-aurora-perfume.jpg",
    notes: {
      top: ["Pitanga Brasileira", "Mandarina Verde"],
      heart: ["Cardamomo Rosé", "Magnólia", "Folhas de Violeta"],
      base: ["Fava Tonka", "Cedro", "Cashmeran"],
    },
    tags: ["vibrante", "especiada", "tropical"],
    collections: ["Red Bloom"],
  },
  {
    id: "hibisco-rubro",
    slug: "hibisco-rubro",
    name: "Hibisco Rubro",
    category: "Parfum",
    description: "Hibisco e rosa damascena infundidos em chá preto defumado.",
    price: 33900,
    priceFormatted: formatPrice(33900),
    image: "/RedCollection/hibiscus-ruby-perfume.jpg",
    notes: {
      top: ["Hibisco Carmim", "Frésia Rubra"],
      heart: ["Rosa Damascena", "Chá Preto", "Peônia Escarlate"],
      base: ["Âmbar Escuro", "Fava Tonka", "Madeira de Ébano"],
    },
    tags: ["floral", "âmbar", "artístico"],
    collections: ["Red Bloom"],
  },
]
