export type Perfume = {
  id: string
  slug: string
  name: string
  category: string
  description: string
  price: number // price in cents
  priceFormatted: string
  image: string
  notes: {
    top: string[]
    heart: string[]
    base: string[]
  }
  tags: string[]
  collections?: string[]
  highlighted?: boolean
  type?: "perfume" | "body-splash"
}

const formatPrice = (value: number) =>
  new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    minimumFractionDigits: 2,
  }).format(value / 100)

export const perfumes: Perfume[] = [
  // ===== PURPLE SOUL =====
  {
    id: "ameixa-noir",
    slug: "ameixa-noir",
    name: "Ameixa Noir",
    category: "Eau de Parfum",
    description: "Notas profundas de ameixa preta envoltas em baunilha dourada e patchouli.",
    price: 28900,
    priceFormatted: formatPrice(28900),
    image: "/purple-plum-perfume-bottle-elegant-gold-details.jpg",
    notes: {
      top: ["ameixa negra", "bergamota"],
      heart: ["baunilha", "jasmim"],
      base: ["patchouli", "ambar"],
    },
    tags: ["intenso", "noturno", "baunilha"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "jabuticaba-mystique",
    slug: "jabuticaba-mystique",
    name: "Jabuticaba Mystique",
    category: "Eau de Parfum",
    description: "Essencia artesanal de jabuticaba com acordes amadeirados sofisticados.",
    price: 32900,
    priceFormatted: formatPrice(32900),
    image: "/jabuticaba-perfume-bottle-luxury-purple-gold.jpg",
    notes: {
      top: ["jabuticaba fresca"],
      heart: ["madeiras nobres", "rosa negra"],
      base: ["cedro", "almiscar"],
    },
    tags: ["amadeirado", "frutado", "exclusivo"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "uva-velvet",
    slug: "uva-velvet",
    name: "Uva Velvet",
    category: "Eau de Parfum",
    description: "Frescor das uvas com notas florais delicadas e toque aveludado.",
    price: 26900,
    priceFormatted: formatPrice(26900),
    image: "/grape-perfume-bottle-elegant-violet-gold-accents.jpg",
    notes: {
      top: ["uvas rubi", "peonia"],
      heart: ["lotus", "magnolia"],
      base: ["almiscar branco"],
    },
    tags: ["aveludado", "floral", "sofisticado"],
    collections: ["Purple Soul"],
  },
  {
    id: "figo-roxo-imperial",
    slug: "figo-roxo-imperial",
    name: "Figo Roxo Imperial",
    category: "Parfum",
    description: "Perfume opulento com figo roxo caramelizado e especiarias orientais.",
    price: 34900,
    priceFormatted: formatPrice(34900),
    image: "/elegant-purple-fig-perfume-bottle-with-gold-detail.jpg",
    notes: {
      top: ["figo roxo", "cardamomo"],
      heart: ["rosa damascena", "violeta"],
      base: ["cedro", "oud"],
    },
    tags: ["especiado", "luxuoso", "oriental"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "amora-sublime",
    slug: "amora-sublime",
    name: "Amora Sublime",
    category: "Eau de Parfum",
    description: "Intensa amora silvestre com toques de rosa bulgara e musk cremoso.",
    price: 30900,
    priceFormatted: formatPrice(30900),
    image: "/blackberry-perfume-bottle-purple-gold-luxury.jpg",
    notes: {
      top: ["amora silvestre", "mandarina"],
      heart: ["rosa bulgara", "ylang-ylang"],
      base: ["almiscar cremoso", "sandalo"],
    },
    tags: ["floral", "romantico", "cremoso"],
    collections: ["Purple Soul"],
  },
  {
    id: "acai-nebular",
    slug: "acai-nebular",
    name: "Acai Nebular",
    category: "Eau de Toilette",
    description: "Vibrante combinacao de acai com notas terrosas e frescor herbal.",
    price: 20300,
    priceFormatted: formatPrice(20300),
    image: "/perfumeFei.png",
    notes: {
      top: ["acai", "limao siciliano"],
      heart: ["folhas verdes", "lavanda"],
      base: ["vetiver", "cedro"],
    },
    tags: ["herbal", "vibrante", "diurno"],
    collections: ["Purple Soul"],
  },
  {
    id: "mirtilo-elegant",
    slug: "mirtilo-elegant",
    name: "Mirtilo Elegant",
    category: "Eau de Parfum",
    description: "Perfume refrescante com mirtilo cristalino e bouquet floral moderno.",
    price: 27900,
    priceFormatted: formatPrice(27900),
    image: "/mirtiloFei.jpeg",
    notes: {
      top: ["mirtilo", "pera"],
      heart: ["iris", "peonia branca"],
      base: ["cashmere", "almiscar"],
    },
    tags: ["refrescante", "moderno", "leve"],
    collections: ["Purple Soul"],
  },
  {
    id: "cereja-roxo-romantica",
    slug: "cereja-roxo-romantica",
    name: "Cereja Roxa Romantica",
    category: "Eau de Parfum",
    description: "Notas suculentas de cereja roxa envolvidas por petalas acetinadas.",
    price: 29900,
    priceFormatted: formatPrice(29900),
    image: "/purple-cherry-perfume-bottle-romantic.jpg",
    notes: {
      top: ["cereja roxa", "groselha"],
      heart: ["rosa centifolia", "lirio"],
      base: ["fava tonka", "cedro branco"],
    },
    tags: ["frutado", "romantico", "doce"],
    collections: ["Purple Soul"],
  },
  {
    id: "groselha-negra-noir",
    slug: "groselha-negra-noir",
    name: "Groselha Negra Noir",
    category: "Parfum",
    description: "Essencia intensa com groselha negra e acorde de couro elegante.",
    price: 31900,
    priceFormatted: formatPrice(31900),
    image: "/black-currant-perfume-bottle-luxury.jpg",
    notes: {
      top: ["groselha negra", "pimenta rosa"],
      heart: ["violeta", "cha preto"],
      base: ["couro", "vetiver"],
    },
    tags: ["dramatico", "couro", "noturno"],
    collections: ["Purple Soul"],
    highlighted: true,
  },
  {
    id: "ameixa-seca-royal",
    slug: "ameixa-seca-royal",
    name: "Ameixa Seca Royal",
    category: "Parfum",
    description: "Fragancia rica com ameixa seca, mel de acacia e incenso dourado.",
    price: 33900,
    priceFormatted: formatPrice(33900),
    image: "/ameixaFeia.jpg",
    notes: {
      top: ["ameixa seca", "cassis"],
      heart: ["mel", "flor de laranjeira"],
      base: ["incenso", "ambar cinza"],
    },
    tags: ["gourmand", "opulento", "quente"],
    collections: ["Purple Soul"],
  },
  {
    id: "sabugueiro-mystic",
    slug: "sabugueiro-mystic",
    name: "Sabugueiro Mystic",
    category: "Eau de Parfum",
    description: "Perfume misterioso com flor de sabugueiro e nuances resinosas.",
    price: 28900,
    priceFormatted: formatPrice(28900),
    image: "/sabugoFei.jpg",
    notes: {
      top: ["flor de sabugueiro", "lima-da-persia"],
      heart: ["incenso branco", "violeta"],
      base: ["resinas ambar", "madeira de cashmere"],
    },
    tags: ["mistico", "resinoso", "artesanal"],
    collections: ["Purple Soul"],
  },
  {
    id: "aronia-power",
    slug: "aronia-power",
    name: "Aronia Power",
    category: "Eau de Toilette",
    description: "Essencia energetica de aronia com especiarias frias e musk limpo.",
    price: 25900,
    priceFormatted: formatPrice(25900),
    image: "/aronia-perfume-bottle-power.jpg",
    notes: {
      top: ["aronia", "pimenta sichuan"],
      heart: ["folha de violeta", "cha branco"],
      base: ["almiscar limpo", "cedro"],
    },
    tags: ["vibrante", "clean", "energetico"],
    collections: ["Purple Soul"],
  },

  // ===== RED BLOOM =====
  {
    id: "framboesa-carmesim",
    slug: "framboesa-carmesim",
    name: "Framboesa Carmesim",
    category: "Eau de Parfum",
    description: "Framboesa madura com lichia cintilante e petalas cristalinas.",
    price: 32900,
    priceFormatted: formatPrice(32900),
    image: "/RedCollection/RasberryFragance.jpg",
    notes: {
      top: ["Framboesa Silvestre", "Lichia Rubra", "Limao Siciliano"],
      heart: ["Petalas Cristalinas", "Magnolia", "Rosa Cha"],
      base: ["Ambar Translucido", "Musk Branco", "Sandalo Leve"],
    },
    tags: ["frutado", "efervescente", "doce"],
    collections: ["Red Bloom"],
    highlighted: true,
  },
  {
    id: "roma-royale",
    slug: "roma-royale",
    name: "Roma Royale",
    category: "Parfum",
    description: "Roma rubra envolta em madeira cerejeira e baunilha tostada.",
    price: 34900,
    priceFormatted: formatPrice(34900),
    image: "/RedCollection/pomegranate-royale-perfume.jpg",
    notes: {
      top: ["Roma Rubra", "Groselha Escura"],
      heart: ["Madeira de Cerejeira", "Jasmim Noite"],
      base: ["Baunilha Dourada", "Patchouli", "Ambar Rubro"],
    },
    tags: ["suculento", "envolvente", "sensual"],
    collections: ["Red Bloom"],
  },
  {
    id: "pitanga-aurora",
    slug: "pitanga-aurora",
    name: "Pitanga Aurora",
    category: "Eau de Parfum",
    description: "Pitanga brasileira vibrante com cardamomo rose e fava tonka.",
    price: 30900,
    priceFormatted: formatPrice(30900),
    image: "/RedCollection/pitanga-aurora-perfume.jpg",
    notes: {
      top: ["Pitanga Brasileira", "Mandarina Verde"],
      heart: ["Cardamomo Rose", "Magnolia", "Folhas de Violeta"],
      base: ["Fava Tonka", "Cedro", "Cashmeran"],
    },
    tags: ["vibrante", "especiada", "tropical"],
    collections: ["Red Bloom"],
  },
  {
    id: "hibisco-rubro",
    slug: "hibisco-rubro",
    name: "Hibisco Rubro",
    category: "Parfum",
    description: "Hibisco e rosa damascena infundidos em cha preto defumado.",
    price: 33900,
    priceFormatted: formatPrice(33900),
    image: "/RedCollection/hibiscus-ruby-perfume.jpg",
    notes: {
      top: ["Hibisco Carmim", "Fresia Rubra"],
      heart: ["Rosa Damascena", "Cha Preto", "Peonia Escarlate"],
      base: ["Ambar Escuro", "Fava Tonka", "Madeira de Ebano"],
    },
    tags: ["floral", "ambar", "artistico"],
    collections: ["Red Bloom"],
  },
  {
    id: "cereja-negra-veludo",
    slug: "cereja-negra-veludo",
    name: "Cereja Negra Veludo",
    category: "Parfum",
    description: "Cereja negra aveludada com acordes de chocolate amargo e rosa turca.",
    price: 35900,
    priceFormatted: formatPrice(35900),
    image: "/red-cherry-perfume-passion.jpg",
    notes: {
      top: ["Cereja Negra", "Bergamota Rubra"],
      heart: ["Rosa Turca", "Chocolate Amargo"],
      base: ["Baunilha Escura", "Oud", "Almiscar Quente"],
    },
    tags: ["gourmand", "sensual", "noturno"],
    collections: ["Red Bloom"],
  },
  {
    id: "morango-imperial",
    slug: "morango-imperial",
    name: "Morango Imperial",
    category: "Eau de Parfum",
    description: "Morango suculento com peonia rosa e acorde de champagne delicado.",
    price: 31900,
    priceFormatted: formatPrice(31900),
    image: "/red-strawberry-perfume-vibrant.jpg",
    notes: {
      top: ["Morango Maduro", "Champanhe Rose"],
      heart: ["Peonia Rosa", "Jasmim Sambac"],
      base: ["Almiscar Cremoso", "Cashmeran", "Cedro Branco"],
    },
    tags: ["frutado", "fresco", "elegante"],
    collections: ["Red Bloom"],
  },

  // ===== GOLDEN AURA =====
  {
    id: "ouro-solar",
    slug: "ouro-solar",
    name: "Ouro Solar",
    category: "Parfum",
    description: "Bergamota italiana cintilante, pimenta rosa e ambar luminoso criam um rastro solar.",
    price: 36900,
    priceFormatted: formatPrice(36900),
    image: "/GoldCollection/ouro-solar-perfume.jpg",
    notes: {
      top: ["Bergamota Italiana", "Pimenta Rosa"],
      heart: ["Flor de Laranjeira", "Neroli", "Lavanda Provencal"],
      base: ["Ambar Solar", "Cedro Dourado", "Musk Radiante"],
    },
    tags: ["citrico", "solar", "especiado"],
    collections: ["Golden Aura"],
    highlighted: true,
  },
  {
    id: "mel-de-safra",
    slug: "mel-de-safra",
    name: "Mel de Safra",
    category: "Parfum",
    description: "Mel de acacia caramelizado encontra flor de laranjeira e sandalo creme artesanal.",
    price: 38900,
    priceFormatted: formatPrice(38900),
    image: "/GoldCollection/mel-safra-perfume.jpg",
    notes: {
      top: ["Mel de Acacia", "Mandarina Doce"],
      heart: ["Flor de Laranjeira", "Gardenia", "Jasmim Mel"],
      base: ["Sandalo Creme", "Baunilha Fava", "Ambar Dourado"],
    },
    tags: ["gourmand", "floral", "cremoso"],
    collections: ["Golden Aura"],
  },
  {
    id: "ambar-aurora",
    slug: "ambar-aurora",
    name: "Ambar Aurora",
    category: "Parfum",
    description: "Ambar resinoso com fava tonka, figo dourado e incenso branco etereo.",
    price: 39900,
    priceFormatted: formatPrice(39900),
    image: "/GoldCollection/amber-aurora-perfume.jpg",
    notes: {
      top: ["Figo Dourado", "Pessego Branco"],
      heart: ["Ambar Vivo", "Benjoim", "Jasmim Absoluto"],
      base: ["Fava Tonka", "Incenso Branco", "Madeira de Cashmere"],
    },
    tags: ["resinoso", "sofisticado", "opulento"],
    collections: ["Golden Aura"],
  },
  {
    id: "champanhe-velours",
    slug: "champanhe-velours",
    name: "Champanhe Velours",
    category: "Eau de Parfum",
    description: "Pera cristalina, champanhe rose e almiscar cremoso para um brilho festivo.",
    price: 41900,
    priceFormatted: formatPrice(41900),
    image: "/GoldCollection/champagne-velours-perfume.jpg",
    notes: {
      top: ["Champanhe Rose", "Pera Cristal", "Framboesa Clara"],
      heart: ["Peonia Rosa", "Flor de Laranjeira", "Iris Aveludada"],
      base: ["Almiscar Cremoso", "Baunilha", "Cedro Branco"],
    },
    tags: ["efervescente", "floral", "aveludado"],
    collections: ["Golden Aura"],
    highlighted: true,
  },
  {
    id: "damasco-real",
    slug: "damasco-real",
    name: "Damasco Real",
    category: "Parfum",
    description: "Damasco maduro com acafrao dourado e sandalo leitoso para uma aura majestosa.",
    price: 37900,
    priceFormatted: formatPrice(37900),
    image: "/golden-apricot-perfume-luxury.jpg",
    notes: {
      top: ["Damasco Maduro", "Acafrao"],
      heart: ["Iris Dourada", "Ylang-Ylang", "Rosa Centifolia"],
      base: ["Sandalo Leitoso", "Ambar Gris", "Musk Dourado"],
    },
    tags: ["oriental", "quente", "luxuoso"],
    collections: ["Golden Aura"],
  },
  {
    id: "pessego-seda",
    slug: "pessego-seda",
    name: "Pessego Seda",
    category: "Eau de Parfum",
    description: "Pessego aveludado com heliotropio e baunilha tonka para suavidade absoluta.",
    price: 35900,
    priceFormatted: formatPrice(35900),
    image: "/golden-peach-perfume-elegant.jpg",
    notes: {
      top: ["Pessego Branco", "Neroli"],
      heart: ["Heliotropio", "Peonia", "Osmanthus"],
      base: ["Baunilha Tonka", "Almiscar Seda", "Cedro"],
    },
    tags: ["aveludado", "feminino", "suave"],
    collections: ["Golden Aura"],
  },

  // ===== BODY SPLASH - PURPLE SOUL =====
  {
    id: "splash-ameixa-noir",
    slug: "splash-ameixa-noir",
    name: "Ameixa Noir Splash",
    category: "Body Splash",
    description: "Versao refrescante da iconica Ameixa Noir com notas frutadas e baunilha leve.",
    price: 8900,
    priceFormatted: formatPrice(8900),
    image: "/purple-plum-perfume-bottle-elegant-gold-details.jpg",
    notes: {
      top: ["ameixa negra", "bergamota fresca"],
      heart: ["baunilha leve", "agua de jasmim"],
      base: ["musk branco"],
    },
    tags: ["refrescante", "frutado", "leve"],
    collections: ["Purple Soul"],
    type: "body-splash",
  },
  {
    id: "splash-jabuticaba",
    slug: "splash-jabuticaba",
    name: "Jabuticaba Fresh Splash",
    category: "Body Splash",
    description: "Jabuticaba cristalina com agua de rosas e frescor herbal para o dia a dia.",
    price: 8900,
    priceFormatted: formatPrice(8900),
    image: "/jabuticaba-perfume-bottle-luxury-purple-gold.jpg",
    notes: {
      top: ["jabuticaba", "limao"],
      heart: ["agua de rosas", "folhas verdes"],
      base: ["cedro leve"],
    },
    tags: ["fresco", "diurno", "natural"],
    collections: ["Purple Soul"],
    type: "body-splash",
  },
  {
    id: "splash-uva-velvet",
    slug: "splash-uva-velvet",
    name: "Uva Velvet Splash",
    category: "Body Splash",
    description: "Uva aveludada com peonia aquosa e almiscar clean para frescor duradouro.",
    price: 7900,
    priceFormatted: formatPrice(7900),
    image: "/grape-perfume-bottle-elegant-violet-gold-accents.jpg",
    notes: {
      top: ["uva fresca", "pera"],
      heart: ["peonia aquosa", "magnolia"],
      base: ["almiscar clean"],
    },
    tags: ["aveludado", "clean", "diurno"],
    collections: ["Purple Soul"],
    type: "body-splash",
  },

  // ===== BODY SPLASH - RED BLOOM =====
  {
    id: "splash-framboesa",
    slug: "splash-framboesa",
    name: "Framboesa Carmesim Splash",
    category: "Body Splash",
    description: "Framboesa cintilante com lichia e agua de rosas para frescor vibrante.",
    price: 8900,
    priceFormatted: formatPrice(8900),
    image: "/RedCollection/RasberryFragance.jpg",
    notes: {
      top: ["framboesa", "lichia"],
      heart: ["agua de rosas", "petalas"],
      base: ["musk leve"],
    },
    tags: ["frutado", "fresco", "vibrante"],
    collections: ["Red Bloom"],
    type: "body-splash",
  },
  {
    id: "splash-morango",
    slug: "splash-morango",
    name: "Morango Imperial Splash",
    category: "Body Splash",
    description: "Morango suculento com champanhe e peonia aquosa para dias ensolarados.",
    price: 8900,
    priceFormatted: formatPrice(8900),
    image: "/red-strawberry-perfume-vibrant.jpg",
    notes: {
      top: ["morango", "champanhe"],
      heart: ["peonia aquosa", "jasmim"],
      base: ["almiscar branco"],
    },
    tags: ["doce", "fresco", "solar"],
    collections: ["Red Bloom"],
    type: "body-splash",
  },
  {
    id: "splash-pitanga",
    slug: "splash-pitanga",
    name: "Pitanga Aurora Splash",
    category: "Body Splash",
    description: "Pitanga tropical com mandarina e folhas verdes para energia natural.",
    price: 7900,
    priceFormatted: formatPrice(7900),
    image: "/RedCollection/pitanga-aurora-perfume.jpg",
    notes: {
      top: ["pitanga", "mandarina"],
      heart: ["folhas verdes", "cardamomo leve"],
      base: ["cedro clean"],
    },
    tags: ["tropical", "energetico", "natural"],
    collections: ["Red Bloom"],
    type: "body-splash",
  },

  // ===== BODY SPLASH - GOLDEN AURA =====
  {
    id: "splash-ouro-solar",
    slug: "splash-ouro-solar",
    name: "Ouro Solar Splash",
    category: "Body Splash",
    description: "Bergamota luminosa com pimenta rosa suave e frescor ambarado.",
    price: 9900,
    priceFormatted: formatPrice(9900),
    image: "/GoldCollection/ouro-solar-perfume.jpg",
    notes: {
      top: ["bergamota", "pimenta rosa"],
      heart: ["neroli", "flor de laranjeira"],
      base: ["ambar leve"],
    },
    tags: ["citrico", "luminoso", "fresco"],
    collections: ["Golden Aura"],
    type: "body-splash",
  },
  {
    id: "splash-champanhe",
    slug: "splash-champanhe",
    name: "Champanhe Velours Splash",
    category: "Body Splash",
    description: "Pera cristalina com champanhe efervescente e almiscar suave.",
    price: 9900,
    priceFormatted: formatPrice(9900),
    image: "/GoldCollection/champagne-velours-perfume.jpg",
    notes: {
      top: ["champanhe", "pera"],
      heart: ["peonia", "iris"],
      base: ["almiscar suave"],
    },
    tags: ["efervescente", "elegante", "leve"],
    collections: ["Golden Aura"],
    type: "body-splash",
  },
  {
    id: "splash-pessego",
    slug: "splash-pessego",
    name: "Pessego Seda Splash",
    category: "Body Splash",
    description: "Pessego aveludado com heliotropio aquoso e baunilha clean.",
    price: 8900,
    priceFormatted: formatPrice(8900),
    image: "/golden-peach-perfume-elegant.jpg",
    notes: {
      top: ["pessego", "neroli"],
      heart: ["heliotropio aquoso", "peonia"],
      base: ["baunilha clean"],
    },
    tags: ["aveludado", "suave", "feminino"],
    collections: ["Golden Aura"],
    type: "body-splash",
  },
]
